name: Luno DCA Analysis

on:
  schedule:
    # Runs every 4 hours (adjust cron schedule as needed)
    # See: https://crontab.guru/every-4-hours
    - cron: '0 7 * * 1'
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  run_analyzer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Use a recent Python 3 version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Luno DCA Analyzer
        env:
          # Luno API Credentials (from secrets)
          LUNO_API_KEY_ID: ${{ secrets.LUNO_API_KEY_ID }}
          LUNO_API_KEY_SECRET: ${{ secrets.LUNO_API_KEY_SECRET }}

          # Email Credentials (from secrets)
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
          EMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }} # Ensure this secret name matches what you create

          # Ensure PYTHONUNBUFFERED is set so output appears in logs immediately
          PYTHONUNBUFFERED: 1
        run: python luno_dca_analyzer.py
